--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ynv/pics/wpps/rw.png"

-- Special
background="#0b0b0b"
foreground="#dde2df"
cursor="#dde2df"

-- Colors
color0="#0b0b0b"
color1="#D30843"
color2="#FB0046"
color3="#738975"
color4="#809381"
color5="#99A99B"
color6="#B8C7BB"
color7="#dde2df"
color8="#9a9e9c"
color9="#D30843"
color10="#FB0046"
color11="#738975"
color12="#809381"
color13="#99A99B"
color14="#B8C7BB"
color15="#dde2df"
