# Shell variables
# Generated by 'wal'
wallpaper='/home/ynv/pics/wpps/rw.png'

# Special
background='#0b0b0b'
foreground='#dde2df'
cursor='#dde2df'

# Colors
color0='#0b0b0b'
color1='#D30843'
color2='#FB0046'
color3='#738975'
color4='#809381'
color5='#99A99B'
color6='#B8C7BB'
color7='#dde2df'
color8='#9a9e9c'
color9='#D30843'
color10='#FB0046'
color11='#738975'
color12='#809381'
color13='#99A99B'
color14='#B8C7BB'
color15='#dde2df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
